# Generated by Django 4.2 on 2023-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='theme id')),
                ('name', models.CharField(max_length=20, verbose_name='theme name')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
            ],
            options={
                'db_table': 'themes',
            },
        ),
    ]
