# Generated by Django 4.1.1 on 2023-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='theme name')),
                ('type', models.IntegerField(verbose_name='theme type')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
            ],
            options={
                'db_table': 'themes',
            },
        ),
    ]
