# Generated by Django 4.1.1 on 2023-05-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.IntegerField(choices=[(0, 'Домашняя работа'), (1, 'Классная работа'), (2, 'Блиц'), (3, 'Домашний письменный экзамен'), (4, 'Домашний устный экзамен'), (5, 'Письменный экзамен'), (6, 'Устный экзамен'), (7, 'Вне статистики')], verbose_name='theme type'),
        ),
    ]
