# Generated by Django 4.1.1 on 2023-05-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_alter_theme_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_homework',
            field=models.BooleanField(default=0, verbose_name='is homework'),
            preserve_default=False,
        ),
    ]
