# Generated by Django 4.1.1 on 2023-05-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_theme_is_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='theme id'),
        ),
    ]
