# Generated by Django 4.2 on 2023-08-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_alter_theme_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_homework',
        ),
    ]
