# Generated by Django 4.2 on 2023-08-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_remove_theme_is_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='type',
        ),
    ]
