# Generated by Django 4.2 on 2023-11-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='user id')),
                ('name', models.CharField(max_length=100, verbose_name='user name')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='user login')),
                ('password', models.CharField(max_length=200, verbose_name='user password')),
                ('experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='student experience')),
                ('mana_earned', models.IntegerField(blank=True, default=0, null=True, verbose_name='mana earned by student')),
                ('last_homework_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='last homework id')),
                ('last_classwork_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='last classwork id')),
                ('is_admin', models.BooleanField(default=0, verbose_name='is this account is admin')),
                ('school_class', models.IntegerField(blank=True, default=None, null=True, verbose_name='student class')),
                ('default_password', models.CharField(blank=True, max_length=5, null=True, verbose_name='default password')),
                ('is_default', models.BooleanField(default=True, verbose_name='is default password')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id группы')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('marker', models.IntegerField(choices=[(0, '#ff8282'), (1, '#ffb875'), (2, '#fdff96'), (3, '#93ff91'), (4, '#78ffef'), (5, '#7776d6'), (6, '#bfa0de'), (7, None)], default=7, null=True, verbose_name='Цвет группы')),
                ('school_class', models.IntegerField(blank=True, default=None, null=True, verbose_name='student class')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id входа')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id группы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_users',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id админа')),
                ('tier', models.IntegerField(choices=[(0, 'Стажер'), (1, 'Администратор'), (2, 'Супер-администратор')], default=0, verbose_name='Цвет группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
