# Generated by Django 5.0.6 on 2024-07-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='user id')),
                ('name', models.CharField(max_length=100, verbose_name='user name')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='user login')),
                ('password', models.CharField(max_length=200, verbose_name='user password')),
                ('experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='total student experience')),
                ('exam_experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='written exam student experience')),
                ('oral_exam_experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='oral exam student experience')),
                ('mana_earned', models.IntegerField(blank=True, default=0, null=True, verbose_name='mana earned by student')),
                ('last_homework_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='last homework id')),
                ('last_classwork_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='last classwork id')),
                ('is_admin', models.BooleanField(default=0, verbose_name='is this account is admin')),
                ('school_class', models.IntegerField(blank=True, default=None, null=True, verbose_name='student class')),
                ('default_password', models.CharField(blank=True, max_length=5, null=True, verbose_name='default password')),
                ('is_default', models.BooleanField(default=True, verbose_name='is default password')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='is user disabled')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id админа')),
                ('tier', models.IntegerField(choices=[(0, 'Стажер'), (1, 'Администратор'), (2, 'Супер-администратор')], default=0, verbose_name='Цвет группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id входа')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
