# Generated by Django 4.2 on 2024-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam_experience',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='written exam student experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='oral_exam_experience',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='oral exam student experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='total student experience'),
        ),
    ]
