# Generated by Django 5.0.6 on 2024-08-03 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 19, 35, 10, 834123, tzinfo=datetime.timezone.utc), verbose_name='user created at'),
        ),
    ]
