# Generated by Django 4.2 on 2023-08-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='group id')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
    ]
