# Generated by Django 4.2 on 2023-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_group_name_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_classwork_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='last classwork id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_homework_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='last homework id'),
        ),
    ]
