# Generated by Django 4.2 on 2023-08-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_last_classwork_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
