# Generated by Django 4.2 on 2023-09-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_experience_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id группы')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('marker', models.IntegerField(choices=[(0, '#ffffff'), (1, '#ff8282'), (2, '#ffb875'), (3, '#fdff96'), (4, '#93ff91'), (5, '#78ffef'), (6, '#7776d6'), (7, '#bfa0de')], default=0, verbose_name='Цвет группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id группы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'group_users',
            },
        ),
    ]
