# Generated by Django 4.2 on 2023-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_groupuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='school_class',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='student class'),
        ),
    ]
