# Generated by Django 4.2 on 2023-09-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_group_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
