# Generated by Django 4.2 on 2023-09-19 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id админа')),
                ('tier', models.IntegerField(choices=[(0, 'Стажер'), (1, 'Администратор'), (2, 'Супер-администратор')], default=0, verbose_name='Цвет группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
