# Generated by Django 4.2 on 2023-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_group_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='marker',
            field=models.IntegerField(choices=[(0, '#ff8282'), (1, '#ffb875'), (2, '#fdff96'), (3, '#93ff91'), (4, '#78ffef'), (5, '#7776d6'), (6, '#bfa0de'), (7, None)], default=7, null=True, verbose_name='Цвет группы'),
        ),
    ]
