# Generated by Django 4.1.1 on 2023-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=30, verbose_name='event operation')),
                ('from_table', models.CharField(max_length=30, verbose_name='event table')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='event date')),
                ('details', models.TextField(default=None, verbose_name='event details')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
