# Generated by Django 4.1.1 on 2023-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana', models.IntegerField(default=0, verbose_name='mana')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('max_score', models.FloatField(default=0, verbose_name='max_score')),
                ('grades', models.CharField(default=None, max_length=200, verbose_name='grades string')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises(current student)')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Mana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=5, verbose_name='mana color(green or blue)')),
                ('is_given', models.BooleanField(default=0, verbose_name='is mana given')),
            ],
            options={
                'db_table': 'mana',
            },
        ),
    ]
