# Generated by Django 5.0.6 on 2024-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('max_score', models.FloatField(default=0, verbose_name='max_score')),
                ('grades', models.JSONField(default=None, verbose_name='grades string')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises(current student)')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Mana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=5, verbose_name='mana color(green or blue)')),
                ('is_given', models.BooleanField(default=0, verbose_name='is mana given')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mana',
            },
        ),
    ]
