# Generated by Django 4.2 on 2023-08-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='mana',
        ),
    ]
