# Generated by Django 5.0.6 on 2024-08-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='grade id'),
        ),
        migrations.AlterField(
            model_name='mana',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='mana id'),
        ),
    ]
