# Generated by Django 4.2 on 2024-02-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='league id')),
                ('name', models.CharField(max_length=100, verbose_name='league name')),
                ('description', models.CharField(default=None, max_length=1000, null=True, verbose_name='league description')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
                ('rating_type', models.IntegerField(choices=[(0, 'Общий рейтинг'), (1, 'Рейтинг письменного экзамена'), (2, 'Рейтинг устного экзамена'), (3, 'Рейтинг репетиций'), (4, 'Другой рейтинг')], default=0, verbose_name='rating type')),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='LeagueUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='league_user id')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='is hidden for student')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leagues_users',
            },
        ),
    ]
