# Generated by Django 4.2 on 2023-11-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='league id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='league name')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='LeagueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.league')),
            ],
            options={
                'db_table': 'leagues_users',
            },
        ),
    ]
