# Generated by Django 4.2 on 2024-02-12 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='league description'),
        ),
        migrations.AddField(
            model_name='league',
            name='rating_type',
            field=models.IntegerField(choices=[(0, 'Общий рейтинг'), (1, 'Рейтинг письменного экзамена'), (2, 'Рейтинг устного экзамена'), (3, 'Рейтинг репетиций'), (4, 'Другой рейтинг')], default=0, verbose_name='rating type'),
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden for student'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, verbose_name='league name'),
        ),
        migrations.AlterUniqueTogether(
            name='leagueuser',
            unique_together={('league', 'user')},
        ),
    ]
