# Generated by Django 4.2 on 2023-08-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpm.apps.homeworks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id домашней работы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок домашней работы')),
                ('text', models.TextField(verbose_name='Текст домашней работы')),
                ('score', models.IntegerField(verbose_name='Максимальный балл за работу')),
                ('grades', models.CharField(max_length=1000, verbose_name='Форма с оценками')),
                ('fields', models.IntegerField(verbose_name='Количество полей в форме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания домашней работы')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Домашняя работа закрыта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='HomeworkUsers',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id связи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Сдал ли работу ученик')),
                ('answers', models.CharField(max_length=1000, verbose_name='Форма с ответами')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homeworks_users',
            },
        ),
        migrations.CreateModel(
            name='HomeworkUsersFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла пользователя')),
                ('file', models.FileField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Файл новости')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworkusers')),
            ],
            options={
                'db_table': 'homeworks_users_files',
            },
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла')),
                ('file', models.FileField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Файл новости')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework')),
            ],
            options={
                'db_table': 'homeworks_files',
            },
        ),
    ]
