# Generated by Django 4.2 on 2023-11-17 14:23

from django.db import migrations, models
import django.db.models.deletion
import kpm.apps.homeworks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id домашней работы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок домашней работы')),
                ('text', models.TextField(verbose_name='Текст домашней работы')),
                ('score', models.IntegerField(verbose_name='Максимальный балл за работу')),
                ('answers', models.CharField(max_length=5000, verbose_name='Форма с ответами')),
                ('fields', models.IntegerField(verbose_name='Количество полей в форме')),
                ('school_class', models.IntegerField(default=4, verbose_name='Класс работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания домашней работы')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Домашняя работа закрыта')),
            ],
            options={
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла')),
                ('file', models.FileField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Файл новости')),
                ('ext', models.CharField(max_length=100, verbose_name='Расширение файла')),
            ],
            options={
                'db_table': 'homeworks_files',
            },
        ),
        migrations.CreateModel(
            name='HomeworkUsers',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id связи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Сдал ли работу ученик')),
                ('comment', models.TextField(default='', verbose_name='Комментарий преподавателя')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверена ли работа')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка за работу')),
                ('answers', models.CharField(max_length=5000, verbose_name='Форма с ответами')),
                ('answered_at', models.DateTimeField(default=None, null=True, verbose_name='Дата ответа')),
                ('checked_at', models.DateTimeField(default=None, null=True, verbose_name='Дата проверки')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата выдачи работы')),
            ],
            options={
                'db_table': 'homeworks_users',
            },
        ),
        migrations.CreateModel(
            name='HomeworkUsersFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла пользователя')),
                ('file', models.FileField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Файл новости')),
                ('ext', models.CharField(max_length=100, verbose_name='Расширение файла')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworkusers')),
            ],
            options={
                'db_table': 'homeworks_users_files',
            },
        ),
    ]
