# Generated by Django 4.2 on 2023-08-19 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpm.apps.homeworks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_group_name_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id домашней работы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок домашней работы')),
                ('text', models.TextField(verbose_name='Текст домашней работы')),
                ('score', models.IntegerField(verbose_name='Максимальный балл за работу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания домашней работы')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Домашняя работа закрыта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='HomeworkImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла')),
                ('image', models.ImageField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Картинка новости')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework')),
            ],
            options={
                'db_table': 'homeworks_images',
            },
        ),
    ]
