# Generated by Django 4.2 on 2023-08-21 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.CreateModel(
            name='HomeworkUsers',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id связи')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homeworks_users',
            },
        ),
    ]
