# Generated by Django 4.2 on 2023-08-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_remove_homework_grades_homework_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='fields',
            new_name='fieldss',
        ),
    ]
