# Generated by Django 4.2 on 2023-08-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_rename_fields_homework_fieldss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='fieldss',
        ),
    ]
