# Generated by Django 4.2 on 2023-08-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_remove_homework_fieldss'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='fields',
            field=models.IntegerField(default=0, verbose_name='Количество полей в форме'),
            preserve_default=False,
        ),
    ]
