# Generated by Django 4.2 on 2023-08-28 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0006_homework_school_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworkusers',
            unique_together={('homework', 'user')},
        ),
    ]
