# Generated by Django 4.2 on 2023-08-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0007_alter_homeworkusers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusers',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка за работу'),
        ),
    ]
