# Generated by Django 4.2 on 2023-08-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0008_homeworkusers_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusers',
            name='answered_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата ответа'),
        ),
    ]
