# Generated by Django 4.2 on 2023-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_homeworkusers_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusers',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверена ли работа'),
        ),
    ]
