# Generated by Django 4.2 on 2023-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0010_homeworkusers_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='answers',
            field=models.CharField(max_length=5000, verbose_name='Форма с ответами'),
        ),
        migrations.AlterField(
            model_name='homeworkusers',
            name='answers',
            field=models.CharField(max_length=5000, verbose_name='Форма с ответами'),
        ),
    ]
