# Generated by Django 4.2 on 2023-08-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0011_alter_homework_answers_alter_homeworkusers_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkusers',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='homeworkusers',
            name='is_done',
        ),
    ]
