# Generated by Django 4.2 on 2023-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0013_homeworkusers_answers_homeworkusers_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusersfile',
            name='ext',
            field=models.CharField(default='', max_length=10, verbose_name='Расширение файла'),
            preserve_default=False,
        ),
    ]
