# Generated by Django 4.2 on 2023-09-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0014_homeworkusersfile_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusers',
            name='comment',
            field=models.TextField(default=None, null=True, verbose_name='Комментарий преподавателя'),
        ),
    ]
