# Generated by Django 4.2 on 2023-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0016_alter_homeworkusers_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfile',
            name='file',
            field=models.FileField(upload_to='homeworks/', verbose_name='Файл новости'),
        ),
        migrations.AlterField(
            model_name='homeworkusersfile',
            name='file',
            field=models.FileField(upload_to='homeworks/', verbose_name='Файл новости'),
        ),
    ]
