# Generated by Django 4.2 on 2023-09-03 21:35

from django.db import migrations, models
import kpm.apps.homeworks.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0018_alter_homeworkfile_file_alter_homeworkusersfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfile',
            name='file',
            field=models.FileField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Файл новости'),
        ),
        migrations.AlterField(
            model_name='homeworkusersfile',
            name='file',
            field=models.FileField(upload_to=kpm.apps.homeworks.models.PathRename('homeworks/'), verbose_name='Файл новости'),
        ),
    ]
