# Generated by Django 4.2 on 2023-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0019_alter_homeworkfile_file_alter_homeworkusersfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfile',
            name='ext',
            field=models.CharField(max_length=100, verbose_name='Расширение файла'),
        ),
    ]
