# Generated by Django 4.2 on 2023-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0020_alter_homeworkfile_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkusersfile',
            name='ext',
            field=models.CharField(max_length=100, verbose_name='Расширение файла'),
        ),
    ]
