# Generated by Django 4.2 on 2023-09-15 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0021_alter_homeworkusersfile_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusers',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL),
        ),
    ]
