# Generated by Django 4.2 on 2023-09-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0022_homeworkusers_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkusers',
            name='checked_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата проверки'),
        ),
    ]
