# Generated by Django 4.2 on 2023-09-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0024_homeworkusers_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkusers',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата выдачи работы'),
        ),
    ]
