# Generated by Django 5.0.6 on 2024-07-17 11:27

import django.db.models.deletion
import kpm.apps.works.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='work id')),
                ('name', models.CharField(max_length=100, verbose_name='work name')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
                ('is_homework', models.BooleanField(verbose_name='is homework')),
                ('type', models.IntegerField(choices=[(0, 'Домашняя работа'), (1, 'Классная работа'), (2, 'Блиц'), (3, 'Письменный экзамен классный'), (4, 'Устный экзамен классный'), (5, 'Письменный экзамен домашний'), (6, 'Устный экзамен домашний'), (7, 'Письменный экзамен домашний(баллы 2007)'), (8, 'Письменный экзамен классный(баллы 2007)'), (9, 'Вне статистики')], default=0, verbose_name='theme type')),
                ('grades', models.JSONField(verbose_name='work grades')),
                ('max_score', models.FloatField(verbose_name='max score')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='has attachments')),
                ('text', models.TextField(verbose_name='Текст домашней работы')),
                ('answers', models.JSONField(verbose_name='Форма с ответами')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Работа закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания работы')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления работы')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.theme')),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='link id')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='works.work')),
                ('work_2007', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_2007', to='works.work')),
            ],
            options={
                'db_table': 'exam_links',
            },
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла')),
                ('file', models.FileField(upload_to=kpm.apps.works.models.PathRename('homeworks/'), verbose_name='Файл работы')),
                ('ext', models.CharField(max_length=100, verbose_name='Расширение файла')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'db_table': 'works_files',
            },
        ),
        migrations.CreateModel(
            name='WorkUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id связи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Сдал ли работу ученик')),
                ('comment', models.TextField(default='', verbose_name='Комментарий преподавателя')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверена ли работа')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка за работу')),
                ('answers', models.JSONField(verbose_name='Форма с ответами')),
                ('answered_at', models.DateTimeField(default=None, null=True, verbose_name='Дата ответа')),
                ('checked_at', models.DateTimeField(default=None, null=True, verbose_name='Дата проверки')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата выдачи работы')),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'db_table': 'works_users',
                'unique_together': {('work', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkUserFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id файла пользователя')),
                ('file', models.FileField(upload_to=kpm.apps.works.models.PathRename('homeworks/'), verbose_name='Файл работы')),
                ('ext', models.CharField(max_length=100, verbose_name='Расширение файла')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.workuser')),
            ],
            options={
                'db_table': 'works_users_files',
            },
        ),
    ]
