# Generated by Django 4.1.1 on 2023-02-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='work name')),
                ('grades', models.CharField(max_length=100, verbose_name='work grades')),
                ('max_score', models.FloatField(verbose_name='max score')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.theme')),
            ],
            options={
                'db_table': 'works',
            },
        ),
    ]
