# Generated by Django 4.2 on 2023-11-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='work id')),
                ('name', models.CharField(max_length=100, verbose_name='work name')),
                ('grades', models.CharField(max_length=100, verbose_name='work grades')),
                ('max_score', models.FloatField(verbose_name='max score')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises')),
                ('school_class', models.IntegerField(default=4, verbose_name='student class')),
                ('is_homework', models.BooleanField(verbose_name='is homework')),
                ('type', models.IntegerField(choices=[(0, 'Домашняя работа'), (1, 'Классная работа'), (2, 'Блиц'), (3, 'Письменный экзамен'), (4, 'Устный экзамен'), (5, 'Письменный экзамен дз'), (6, 'Устный экзамен дз'), (7, 'Письменный экзамен дз(баллы 2007)'), (8, 'Вне статистики')], default=0, verbose_name='theme type')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания работы')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления работы')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.theme')),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='link id')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='works.work')),
                ('work_2007', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_2007', to='works.work')),
            ],
            options={
                'db_table': 'exam_links',
            },
        ),
    ]
