# Generated by Django 4.2 on 2023-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.IntegerField(choices=[(0, 'Домашняя работа'), (1, 'Классная работа'), (2, 'Блиц'), (3, 'Письменный экзамен'), (4, 'Устный экзамен'), (5, 'Письменный экзамен дз'), (6, 'Устный экзамен дз'), (7, 'Письменный экзамен домашний(баллы 2007)'), (8, 'Письменный экзамен классный(баллы 2007)'), (9, 'Вне статистики')], default=0, verbose_name='theme type'),
        ),
    ]
