# Generated by Django 5.0.6 on 2024-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='answers',
            field=models.JSONField(blank=True, null=True, verbose_name='Форма с ответами'),
        ),
        migrations.AlterField(
            model_name='work',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст домашней работы'),
        ),
    ]
