# Generated by Django 4.1.1 on 2023-05-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='work id'),
        ),
    ]
