# Generated by Django 5.0.6 on 2024-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_work_answers_alter_work_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workuser',
            name='score',
        ),
    ]
