# Generated by Django 4.2 on 2023-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_work_is_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='is_homework',
            field=models.BooleanField(verbose_name='is homework'),
        ),
    ]
