# Generated by Django 5.0.6 on 2024-08-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_remove_workuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='workuser',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта ли работа'),
        ),
    ]
