# Generated by Django 4.2 on 2023-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_work_is_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.IntegerField(choices=[(0, 'Домашняя работа'), (1, 'Классная работа'), (2, 'Блиц'), (3, 'Домашний письменный экзамен'), (4, 'Домашний устный экзамен'), (5, 'Письменный экзамен'), (6, 'Устный экзамен'), (7, 'Вне статистики')], default=0, verbose_name='theme type'),
        ),
    ]
