# Generated by Django 5.0.6 on 2024-08-17 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_work_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workuser',
            name='checker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workuser',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий преподавателя'),
        ),
    ]
