# Generated by Django 4.2 on 2023-08-21 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_work_added_at_alter_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата обновления работы'),
            preserve_default=False,
        ),
    ]
