# Generated by Django 5.0.6 on 2024-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_alter_workuser_checker_alter_workuser_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workuser',
            name='answered_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='workuser',
            name='checked_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата проверки'),
        ),
    ]
