# Generated by Django 4.2 on 2023-08-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_work_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.IntegerField(choices=[(0, 'Домашняя работа'), (1, 'Классная работа'), (2, 'Блиц'), (3, 'Письменный экзамен'), (4, 'Устный экзамен'), (5, 'Письменный экзамен дз'), (6, 'Устный экзамен дз'), (7, 'Письменный экзамен дз(баллы 2007)'), (8, 'Вне статистики')], default=0, verbose_name='theme type'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='link id')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='works.work')),
                ('work_2007', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_2007', to='works.work')),
            ],
            options={
                'db_table': 'exam_links',
            },
        ),
    ]
