# Generated by Django 5.0.6 on 2024-08-28 15:06

import kpm.apps.works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_alter_work_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfile',
            name='file',
            field=models.FileField(upload_to=kpm.apps.works.models.PathRename('homeworks/service/'), verbose_name='Файл работы'),
        ),
        migrations.AlterField(
            model_name='workuserfile',
            name='file',
            field=models.FileField(upload_to=kpm.apps.works.models.PathRename('homeworks/users/'), verbose_name='Файл работы'),
        ),
    ]
