# Generated by Django 5.0.6 on 2024-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_alter_workfile_file_alter_workuserfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидает сдачи'), (1, 'Ожидает проверки'), (2, 'Проверена'), (3, 'Возвращена с комментарием'), (4, 'Просрочена'), (5, 'Просрочена и ожидает проверки'), (6, 'Просрочена и проверена')], default=0, verbose_name='Статус работы'),
        ),
    ]
