# Generated by Django 5.0.6 on 2024-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_work_course_alter_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='course',
            field=models.IntegerField(choices=[(0, '4 класс'), (1, 'Продвинутый'), (2, 'Углубленный'), (3, 'Углубленный алгебра'), (4, 'Углубленный геометрия'), (5, 'Практикум'), (6, 'Алгебра'), (7, 'Геометрия')], verbose_name='course'),
        ),
    ]
