# Generated by Django 5.0.6 on 2024-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id группы')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('marker', models.CharField(default=None, max_length=7, null=True, verbose_name='Цвет группы')),
                ('school_class', models.IntegerField(blank=True, default=None, null=True, verbose_name='student class')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id подгруппы')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('marker', models.CharField(default=None, max_length=7, null=True, verbose_name='Цвет группы')),
                ('school_class', models.IntegerField(blank=True, default=None, null=True, verbose_name='student class')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'subgroups',
            },
        ),
    ]
