# Generated by Django 5.0.6 on 2024-07-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='marker',
            field=models.CharField(default=None, max_length=7, null=True, verbose_name='Цвет подгруппы'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название подгруппы'),
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id пары группа - ученик')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'groups_users',
            },
        ),
        migrations.CreateModel(
            name='SubgroupWorkDates',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id даты выдачи работы')),
                ('date', models.DateField(verbose_name='Дата выдачи работы')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.subgroup')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'db_table': 'subgroup_dates',
                'unique_together': {('subgroup', 'work', 'date')},
            },
        ),
    ]
