# Generated by Django 5.0.6 on 2024-07-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_subgroup_marker_alter_subgroup_name_groupuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubgroupUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id пары подгруппа - ученик')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.subgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subgroups_users',
                'unique_together': {('subgroup', 'user')},
            },
        ),
    ]
