# Generated by Django 5.0.6 on 2024-07-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groupuser_user'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupworkdates',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='subgroupuser',
            name='subgroup',
        ),
        migrations.AlterUniqueTogether(
            name='subgroupuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subgroupuser',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subgroupworkdates',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subgroupworkdates',
            name='work',
        ),
        migrations.CreateModel(
            name='GroupWorkDate',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id тройки группа - дата - работа')),
                ('date', models.DateField(verbose_name='Дата выполнения работы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'db_table': 'groups_works_dates',
            },
        ),
        migrations.DeleteModel(
            name='Subgroup',
        ),
        migrations.DeleteModel(
            name='SubgroupUser',
        ),
        migrations.DeleteModel(
            name='SubgroupWorkDates',
        ),
    ]
