# Generated by Django 5.0.6 on 2024-07-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_subgroupworkdates_subgroup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupWorkDate',
        ),
    ]
