# Generated by Django 5.0.6 on 2024-07-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_delete_groupworkdate'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorkDate',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id тройки группа - дата - работа')),
                ('date', models.DateField(verbose_name='Дата выполнения работы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'db_table': 'groups_works_dates',
            },
        ),
    ]
