# Generated by Django 5.0.6 on 2024-07-21 11:37

import django.db.models.deletion
import kpm.apps.groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_groupuser_user'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorkFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id тройки файла классной работы подгруппы')),
                ('file', models.FileField(upload_to=kpm.apps.groups.models.PathRename('classworks/'), verbose_name='Файл работы')),
                ('ext', models.CharField(max_length=100, verbose_name='Расширение файла')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки файла')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'db_table': 'classworks_files',
            },
        ),
    ]
