# Generated by Django 5.0.6 on 2024-07-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groupworkfile'),
        ('works', '0002_alter_work_answers_alter_work_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupworkdate',
            unique_together={('group', 'work')},
        ),
    ]
