# Generated by Django 5.0.6 on 2024-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_groupworkdate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupworkdate',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения работы'),
        ),
    ]
