# Generated by Django 5.0.6 on 2024-08-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_alter_groupworkdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkdate',
            name='is_given',
            field=models.BooleanField(default=False, verbose_name='Отработала ли таска'),
        ),
    ]
