# Generated by Django 5.0.6 on 2024-08-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='marker',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, verbose_name='Цвет группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Тип группы'),
        ),
    ]
