# Generated by Django 5.0.6 on 2024-08-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_alter_group_marker_alter_group_type'),
        ('works', '0010_alter_workfile_file_alter_workuserfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupworkdate',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
