# Generated by Django 4.2 on 2023-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='message id')),
                ('text', models.TextField(verbose_name='message text')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='has the message been read by the recipient')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='message datetime')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
