# Generated by Django 5.0.6 on 2024-07-17 11:27

import kpm.apps.messages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='message id')),
                ('title', models.CharField(max_length=100, verbose_name='message theme')),
                ('text', models.TextField(verbose_name='message text')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='has the message been read by the recipient')),
                ('viewed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='datetime of view')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='group id')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='group datetime')),
            ],
            options={
                'db_table': 'messages_groups',
            },
        ),
        migrations.CreateModel(
            name='MessageGroupFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='message file id')),
                ('file', models.FileField(upload_to=kpm.apps.messages.models.PathRename('messages/'), verbose_name='Файл работы')),
                ('ext', models.CharField(max_length=100, verbose_name='Расширение файла')),
            ],
            options={
                'db_table': 'messages_group_files',
            },
        ),
    ]
