# Generated by Django 4.2 on 2023-11-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_', '0003_messagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messages_.messagegroup'),
            preserve_default=False,
        ),
    ]
