# Generated by Django 4.2 on 2023-11-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_', '0004_message_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_id',
            new_name='group',
        ),
    ]
