# Generated by Django 4.2 on 2023-11-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_', '0005_rename_group_id_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='datetime',
        ),
    ]
